	# path to the working directory
BASEDIR=/home/nikolai/Software/redkmer

CWD=/simulateddataset/complex

	# path to the male pacbio read data
pacDIR=testreadspac
pacM=${CWD}/${pacDIR}/m_pac.fasta

	# path to the illumina data
illDIR=testreadsill

	# path to the male and female illumina reads
illM=${CWD}/${illDIR}/m.fastq
illF=${CWD}/${illDIR}/f.fastq

	# path to the mitochondrial Reference
#mtREF=${CWD}/MtRef.fasta
