	# path to the working directories
BASEDIR=/srv/babylon/redkmer/redkmer
CWD=simulateddatasets/simple
echo "Rworkdir <- \"${BASEDIR}/${CWD}\"" > path.R

	# path to the male pacbio data
pacDIR=testreadspac
pacM=${CWD}/${pacDIR}/m_pac.fasta

	# path to the illumina data
illDIR=testreadsill
illM=${CWD}/${illDIR}/m.fastq
illF=${CWD}/${illDIR}/f.fastq

	# path to the mitochondrial Reference
MtREF=${CWD}/refgenome/M.fasta

# path to genome assembly if available - needed to step 6
genome=$CWD/refgenome/MaleGenome.fasta

# length cuttoff for pacBIO reads to be included in bins
pac_length=2000

# length normalized sum of illumina reads mapping of pacBio reads cutoff
LSum=50

#kmer X chromosome specificity index (0= no specificity; 1= full X specificity; 0.5= half of the kmer hits are on other chromosomes
XSI=0.9

#define minimum CQ value for X chromosome reads/kmers  = maximum CQ value for autosomal reads/kmers
xmin=1.5

#define maximum CQ value for X chromosome reads/kmers  = minimum  CQ value for GA reads/kmer
xmax=10

#define maximum CQ value for Y chromosome reads/kmers = minimum CQ value for autosomal reads/kmers
ymax=0.2

echo "xmin <-"$xmin"" >> path.R
echo "xmax <-"$xmax"" >> path.R
echo "ymax <-"$ymax"" >> path.R
