	# path to the working directories
BASEDIR=/home/nikolai/Software/redkmer
CWD=simulateddatasets/simple
echo "Rworkdir <- \"${BASEDIR}/${CWD}\"" > path.R

	# path to the male pacbio data
pacDIR=testreadspac
pacM=${CWD}/${pacDIR}/m_pac.fasta

	# path to the illumina data
illDIR=testreadsill
illM=${CWD}/${illDIR}/m.fastq
illF=${CWD}/${illDIR}/f.fastq

	# path to the mitochondrial Reference
MtREF=${CWD}/refgenome/M.fasta
