	# path to the working directory
BASEDIR=/home/nikolai/Software/redkmer

#80kb chroms, 8k illumina/chrom, no errors, no X-repeats
CWD=testproject

#80kb chroms, 8k illumina/chrom, no errors, with X-repeats
CWD=testproject_XR

#80kb chroms, 8k illumina/chrom, with 0.001 error, with X-repeats
CWD=testproject_XR_err


	# path to the male pacbio read data
pacDIR=testreadspac
pacM=${CWD}/${pacDIR}/m_pac.fasta

	# path to the illumina data
illDIR=testreadsill

	# path to the male and female illumina reads
illM=${CWD}/${illDIR}/m.fastq
illF=${CWD}/${illDIR}/f.fastq

	# path to the mitochondrial Reference
mtREF=${CWD}/MtRef.fasta
