	# path to the working directory
BASEDIR=/home/nikolai/Software/redkmer

#80kb chroms @5x coverage, 10k illumina/chrom, no errors, no X-repeats
CWD=testproject

#80kb chroms @5x coverage, 10k illumina/chrom, no errors, with X-repeats
#CWD=testproject_XR

#80kb chroms @5x coverage, 10k illumina/chrom, with errors, with X-repeats
#CWD=testproject_XR_err

#80kb chroms @5x coverage, 10k illumina/chrom, with errors, with degenerate X-repeats
#CWD=testproject_XRdegen_err


	# path to the male pacbio read data
pacDIR=testreadspac
pacM=${CWD}/${pacDIR}/m_pac.fasta

	# path to the illumina data
illDIR=testreadsill

	# path to the male and female illumina reads
illM=${CWD}/${illDIR}/m.fastq
illF=${CWD}/${illDIR}/f.fastq

	# path to the mitochondrial Reference
mtREF=${CWD}/MtRef.fasta
